### ISSUE TITLE
RuntimeError: result type Long can't be cast to the desired output type Bool

### ISSUE THREAD

**Issue by dedelecoder** [Kai-46/PhySG#1]
Hello,

I am trying your example and i have the following error :
PhySG-master\code\model\ray_tracing.py", line 265, in rootfind
    while work_mask.any() & i < self.n_rootfind_steps:
RuntimeError: result type Long can't be cast to the desired output type Bool

Can you help?

Best regards

**Comment by dhawals1939** [comment]
Change the `work_mask.any()` to `work_mask.any().item()` should do the trick I guess.
