### ISSUE TITLE
Setting SG parameter for NDF

### ISSUE THREAD

**Issue by HollyDQWang** [Kai-46/PhySG#13]
Thanks for the great work and releasing the code! 

A quick question for the renderer: in [line 175](https://github.com/Kai-46/PhySG/blob/971a014cbb40b500b61b838a0d2b01220f5feab2/code/model/sg_render.py#L175) of sg_rendering.py, why did you use $\frac{1}{roughness ^4 \cdot \pi}$ instead of 1 as the value of $\mu$? Are you using Blinn-Phong's model for the shape of D?

**Comment by Kai-46** [comment]
We use disney BRDF; and that \mu term is for energy conservation in this BRDF, I think.

**Comment by HollyDQWang** [comment]
I see, thanks so much for the reply! I realized that it is consistent with [this Cornell paper on microfacet brdf.](https://www.graphics.cornell.edu/~bjw/microfacetbsdf.pdf).

May I ask if you have a source code reference for this part? I checked the Disney paper and I don’t think there’s official code released.

**Comment by Kai-46** [comment]
You might want to check Eq. 8.9 on this page: https://www.pbr-book.org/3ed-2018/Reflection_Models/Microfacet_Models . Note that alpha in that equation equals roughness^2 in this PhySG codebase.

**Comment by HollyDQWang** [comment]
Thanks so much! I now see that the alpha term is consistent with definition in Disney brdf :)
