### ISSUE TITLE
Preparing DTU Dataset

### ISSUE THREAD

**Issue by ThreeSRR** [Kai-46/PhySG#14]
Dear authors, I noticed that you did experiments on DTU dataset. But I am wondering how to prepare the proper DTU Dataset to fit the model. Could you please provide the preprocessed  `scan114 buddha object` dataset or provide the script to prepare the DTU dataset. Thx.

**Comment by AetherZ25** [comment]
Hi, have you conducted experiments on the DTU dataset yet? Can you share some of your experiences?
