### ISSUE TITLE
gamma settings for png file

### ISSUE THREAD

**Issue by wenzhengchen** [Kai-46/PhySG#4]
Hi Kai,

Thanks for releasing code for this awesome work!   We are trying to apply physg to nerf images which are basically png files instead of exr files.  I wonder in such a case, how do we set the gamma? Could we simply set it as 2.2 for png/jpg images that are in sRGB space?

Thank you!

Best,
Wenzheng

**Comment by Kai-46** [comment]
yes, setting gamma=2.2 is expected for png ldr images.
